name: Repo File Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: 39 3 * * *

jobs:
  repo_file_sync:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2

      - name: Dependabot automation
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            domdomegg/airconsole-you-talking-to-me
            domdomegg/analytics-lambda
          FILES: |
            file-sync/auto-dependabot.yaml=.github/workflows/auto-dependabot.yaml
          TOKEN: ${{ secrets.PAT }}
