name: Repo Settings Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: 39 3 * * *

jobs:
  repo_settings_sync:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Repo Settings Sync
        uses: kbrashears5/github-action-repo-settings-sync@v1.2
        with:
          REPOSITORIES: "ALL"
          ALLOW_ISSUES: "true"
          ALLOW_PROJECTS: "false"
          ALLOW_WIKI: "false"
          SQUASH_MERGE: "true"
          MERGE_COMMIT: "false"
          REBASE_MERGE: "false"
          AUTO_MERGE: "true"
          DELETE_HEAD: "true"
          BRANCH_PROTECTION_NAME: "master"
          BRANCH_PROTECTION_REQUIRED_REVIEWERS: "1"
          BRANCH_PROTECTION_DISMISS: "false"
          BRANCH_PROTECTION_CODE_OWNERS: "true"
          BRANCH_PROTECTION_ENFORCE_ADMINS: "false"
          TOKEN: ${{ secrets.PAT }}
