name: Repo File Sync

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 39 3 * * *

jobs:
  repo_file_sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2

      # Set up a branch protection rule on the default branch first
      # (otherwise you might merge things that fail checks). Usually:
      # - Require a pull request before merging
      #   - Uncheck 'Require approvals'
      #   - Require review from Code Owners
      # - Require status checks to pass before merging
      #   (select required checks)
      - name: Dependabot automation
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            domdomegg/typescript-library-template
            domdomegg/eslint-config-domdomegg
            domdomegg/airconsole-you-talking-to-me
            domdomegg/analytics-lambda
            domdomegg/aws-ses-v2-local
            domdomegg/ottie
            domdomegg/dealer-tech
            domdomegg/discord-reminder-template
            domdomegg/gdoc2latex
            domdomegg/gdoc2latex-gui
            domdomegg/google-calendar-quickerstart
            domdomegg/google-calendar-to-unitemps
            domdomegg/google-play-version-poller
            domdomegg/halifax-share-dealing-google-sheets
            domdomegg/halifax-share-dealing-sdk
            domdomegg/lifx-houseparty
            domdomegg/london-cycle-parking
            domdomegg/rsa-securid
            domdomegg/rsa-securid-browser-extension
            domdomegg/serverless-offline-ses-v2
            domdomegg/simple16
            domdomegg/spam-email-replier
            domdomegg/ts-i18n
            domdomegg/ts-i18n-webpack-plugin
            domdomegg/ts-i18n-webpack-plugin-example
            domdomegg/ts-i18n-craco-example
            domdomegg/github-actions-timeslots
            domdomegg/uGrBHohIgQY-analysis
            domdomegg/unitemps-sdk
            domdomegg/pdf-scanner
            domdomegg/headless-ui-dialog-centering
            domdomegg/react-typescript-tetris
            domdomegg/postal-vote
            domdomegg/shrolebot
            domdomegg/serverless-offline-watcher
            domdomegg/serverless-example-send-email-with-ses-offline
            domdomegg/github-repo-settings-editor
            domdomegg/pruver
            domdomegg/eggbot
            domdomegg/hindley-milner-typescript
            domdomegg/hindley-milner-typescript-minimal
            domdomegg/domdomegg.github.io
            domdomegg/slack-workflow-pack
            domdomegg/recma-mdx-displayname
            domdomegg/recma-mdx-frontmatter
            domdomegg/process-wrapper
            domdomegg/tsc-absolute
            domdomegg/dynamodb-local-shareddb-bug
            domdomegg/odir
            domdomegg/markdown-inline-preview-vscode
            domdomegg/estree-util-value-to-estree-cjs
            domdomegg/llm-spelling-experiment
            domdomegg/airtable-ts
            domdomegg/airtable-ts-codegen
            domdomegg/airtable-ts-formula
            domdomegg/tsconfig-domdomegg
            domdomegg/weekly-availabilities
            domdomegg/weekly-availabilities-summary
            domdomegg/benchmark-next-vs-nginx
            domdomegg/homelab
            domdomegg/optoma-ir-to-nec
            domdomegg/jimp-1325-mre
            domdomegg/typescript-webapp-template
            domdomegg/google-client-id-lookup
            domdomegg/airtable-mcp-server
            domdomegg/computer-use-mcp
            domdomegg/tsup-831
            domdomegg/parallel-sort
            domdomegg/defuddle-fetch-mcp-server
            domdomegg/just-one-ai-webapp
          FILES: |
            file-sync/auto-dependabot.yaml=.github/workflows/auto-dependabot.yaml
          TOKEN: ${{ secrets.PAT }}
          GIT_EMAIL: domdomegg+git@gmail.com
          GIT_USERNAME: Adam Jones

      - name: Node.js GitHub Pages template
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            domdomegg/pdf-scanner
            domdomegg/headless-ui-dialog-centering
            domdomegg/ts-i18n-webpack-plugin-example
            domdomegg/ts-i18n-craco-example
            domdomegg/gdoc2latex-gui
            domdomegg/airconsole-you-talking-to-me
            domdomegg/react-typescript-tetris
            domdomegg/domdomegg.github.io
            domdomegg/optoma-ir-to-nec
            domdomegg/typescript-webapp-template
            domdomegg/google-client-id-lookup
            domdomegg/just-one-ai-webapp
          FILES: |
            file-sync/node-gh-pages.yaml=.github/workflows/ci.yaml
          TOKEN: ${{ secrets.PAT }}
          GIT_EMAIL: domdomegg+git@gmail.com
          GIT_USERNAME: Adam Jones

      - name: Node.js general template
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            domdomegg/typescript-library-template
            domdomegg/eslint-config-domdomegg
            domdomegg/aws-ses-v2-local
            domdomegg/serverless-offline-ses-v2
            domdomegg/serverless-example-send-email-with-ses-offline
            domdomegg/serverless-offline-watcher
            domdomegg/rsa-securid
            domdomegg/ts-i18n
            domdomegg/ts-i18n-webpack-plugin
            domdomegg/halifax-share-dealing-sdk
            domdomegg/halifax-share-dealing-google-sheets
            domdomegg/gdoc2latex
            domdomegg/github-repo-settings-editor
            domdomegg/unitemps-sdk
            domdomegg/discord-reminder-template
            domdomegg/google-calendar-quickerstart
            domdomegg/google-calendar-to-unitemps
            domdomegg/google-play-version-poller
            domdomegg/spam-email-replier
            domdomegg/hindley-milner-typescript
            domdomegg/hindley-milner-typescript-minimal
            domdomegg/slack-workflow-pack
            domdomegg/recma-mdx-displayname
            domdomegg/recma-mdx-frontmatter
            domdomegg/process-wrapper
            domdomegg/tsc-absolute
            domdomegg/estree-util-value-to-estree-cjs
            domdomegg/llm-spelling-experiment
            domdomegg/airtable-ts
            domdomegg/airtable-ts-codegen
            domdomegg/airtable-ts-formula
            domdomegg/tsconfig-domdomegg
            domdomegg/weekly-availabilities
            domdomegg/weekly-availabilities-summary
            domdomegg/benchmark-next-vs-nginx
            domdomegg/airtable-mcp-server
            domdomegg/computer-use-mcp
            domdomegg/parallel-sort
            domdomegg/defuddle-fetch-mcp-server
          FILES: |
            file-sync/node-general.yaml=.github/workflows/ci.yaml
          TOKEN: ${{ secrets.PAT }}
          GIT_EMAIL: domdomegg+git@gmail.com
          GIT_USERNAME: Adam Jones
