name: Repo Settings Sync

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 39 3 * * *

jobs:
  repo_settings_sync:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Repo Settings Sync
        uses: kbrashears5/github-action-repo-settings-sync@0f0972e91538a186f406cf2df879f5af2615ecba
        with:
          REPOSITORIES: "ALL"
          ALLOW_ISSUES: "true"
          ALLOW_PROJECTS: "false"
          ALLOW_WIKI: "false"
          SQUASH_MERGE: "true"
          MERGE_COMMIT: "false"
          REBASE_MERGE: "false"
          AUTO_MERGE: "true"
          DELETE_HEAD: "true"
          BRANCH_PROTECTION_ENABLED: 'UNCHANGED'
          TOKEN: ${{ secrets.PAT }}
